import type { StaticImageData } from "next/image";
import portrait from "@/assets/asim-headshot2.png";
import aboutPortrait from "@/assets/about-portrait.jpg";
import surfaceHero from "@/assets/Surface.svg";

/**
 * Canonical media. Portrait is imported from src/assets so Next can optimize it.
 * Logo/favicon remain public/ paths (referenced by URL).
 */
export const SITE_ORIGIN = "https://thectomentor.com" as const;

/** Editorial headshot — used by book and author card. */
export const PORTRAIT_SRC: StaticImageData = portrait;

export const PORTRAIT_ALT = "Asim Mohammad" as const;

/** About-page portrait only. */
export const ABOUT_PORTRAIT_SRC: StaticImageData = aboutPortrait;

/**
 * Homepage hero visual — Surface diagram (homepage only).
 * SVG import resolves to a URL string under Next’s webpack asset pipeline.
 */
export const HOME_HERO_SRC: string =
  typeof surfaceHero === "string" ? surfaceHero : (surfaceHero as StaticImageData).src;

export const HOME_HERO_ALT =
  "Four technology risks: incomplete due diligence, unforeseen technical debt, integration challenges, and scalability concerns" as const;

/** Asset exists, but the live Nav/Footer render a text wordmark — nothing renders this yet. */
export const LOGO_SRC = "/logo.svg" as const;

export const FAVICON_SRC = "/favicon.svg" as const;

/** Generated by `src/app/opengraph-image.tsx` — prefer this over the portrait for shares. */
export const SITE_OG_PATH = "/opengraph-image" as const;

export function absoluteUrl(path: string): string {
  if (/^https?:\/\//i.test(path)) return path;
  const normalized = path.startsWith("/") ? path : `/${path}`;
  return `${SITE_ORIGIN}${normalized}`;
}
