/**
 * Canonical public media paths. Swap PORTRAIT_SRC when the editorial shoot lands —
 * every consumer imports from here so paths cannot drift.
 */
export const SITE_ORIGIN = "https://thectomentor.com" as const;

/** Temporary stand-in. Replace with `/portraits/asim-final.jpg` when committed to /public. */
export const PORTRAIT_SRC = "/portraits/hero-placeholder.svg" as const;

export const PORTRAIT_ALT = "Asim Mohammad" as const;

export const LOGO_SRC = "/logo.svg" as const;

export const FAVICON_SRC = "/favicon.svg" as const;

/** Generated by `src/app/opengraph-image.tsx` — prefer this over the portrait for shares. */
export const SITE_OG_PATH = "/opengraph-image" as const;

export function absoluteUrl(path: string): string {
  if (/^https?:\/\//i.test(path)) return path;
  const normalized = path.startsWith("/") ? path : `/${path}`;
  return `${SITE_ORIGIN}${normalized}`;
}
